### ISSUE TITLE
strange results

### ISSUE THREAD

**Issue by AminSahebi** [OpenCilk/productivity-tools#15]
Hi there, 

Thanks for your great work, really appreciate it. Very straightforward and useful work for study parallelism and scalability of a given algorithm (or application). 
However, as you explained in the youtube video-> [the linke](https://youtu.be/a6LMdpHKW34?t=9138) (qsort and BFS with Ligra) I tried to plot the scalability with some applications: such as qsort, fib, matrix-multiplication, and some graph algorithms such as BFS and Pagerank with Ligra as you discussed in the presentation. However, I always sit below the burdened-DAG which is the lowest possible speedup based on the algorithm! which is strange especially for simple ones like fib. 
do I have to do some optimization ( which does not make sense since I want to explore the given algorithm without any optimization how is possible to settle below the lowest possible speedup)?

I really appreciate it if you help me and shed some light on this since there is no written documentation and what I caught was from the presentation video on youtube, maybe I missed or forgotten some parts. 

![image](https://user-images.githubusercontent.com/35843619/112007676-25d99780-8b25-11eb-8f70-694483ac857e.png)
btw, from the csv file, the span bound and parallelism for some well-studied examples like fib is too small! 

Thanks

**Comment by neboat** [comment]
Hey Amin,

Thanks for trying out OpenCilk and for reaching out!

It is indeed strange to see the observed speedup for an application like fib fall below the burdened-dag bound.  There are some common reasons that a program in general can exhibit speedup below this bound — such as memory bandwidth limitations on the system or contention in the program — but those reasons don't apply to fib.  I don't think you're doing anything wrong in how you're using Cilkscale; you shouldn't need any particular optimizations.

I'm not completely sure what's causing the performance you're seeing, but my current guess would be DVFS (dynamic voltage and frequency scaling) on the processor.  In particular, I'm guessing that DVFS might be decreasing the clock frequency of the processor cores in use when the Cilk program uses more workers.  Do you know if the system you're running on supports DVFS (or Intel TurboBoost, for that matter), and if that feature is enabled?

I'm curious what span bounds and parallelism values you're observing that are too small.  Cilkscale's span and parallelism measurements are affected by measurement error and performance noise on the system.  Especially on computations with very small span values, such as fib, this noise can significantly increase the measured span.  Nevertheless, we have generally found these measurements to be good enough for detecting when a program has ample parallelism, and therefore, should theoretically get linear speedup on parallel processors.

Hope that helps.  Let us know if you have more questions.

Cheers,
TB

**Comment by AminSahebi** [comment]
Dear Tao,

Many thanks for your quick reply and your suggestion,
in these days I tried to repeat the experiment with different examples to be sure that there is not any programming mistake,
In the end, I moved to another PC, which has 48 cores,(both PCs are AMD Opteron), other environments are the same, however, the results are different, below are two experiments with Fibonacci and Blocked Matrix Multiplication, 

Here is the Fibonacci 45:
![fibxcilk](https://user-images.githubusercontent.com/35843619/112692131-bd6d1c00-8e7e-11eb-9433-24bb835e172f.png)

Here is the Blocked Matrix Multiplication(MatrixSize 1K, BlockSize 4):
![mmxcilk](https://user-images.githubusercontent.com/35843619/112692145-c362fd00-8e7e-11eb-95bf-8f64b6edee35.png)

So the results seem reasonable, I have some other questions:

What is the reason that the left figure which is the execution time, the observation, and Burdened-DAG are tightly coupled to each other but on the right, for the speed up, the observation is scattered? Shouldn't these two figures should say one thing? 

The previous Machine that I got strange results has 64 cores, however, the tool just recognizes 32 of them, I followed the output and arrived at this point that after "lscpu --parse" called, the runner walks through this output differently from what is happening with 48 cores in the runner.py code. 
https://github.com/OpenCilk/productivity-tools/blob/153a1e05ef3554d44f9ee4eb4bf614b67d709c8c/Cilkscale_vis/runner.py#L60

Both experiments are done with identical docker images available in the opencilk repository. not sure what's the problem, I looked into python code not sure is a python bug or sth else since the two machines are identical, docker images are the same. 
I think the way how the tool recognizes the cores of the CPU is the source of the problem. 

Many thanks
Amin

**Comment by neboat** [comment]
Hey Amin,

Glad to hear you were able to get reasonable results on one of your machines!

Concerning the two figures, it's worth noting that the figure on the left plots running times, while the figure on the right plots speedups compared to the 1-processor running time.  Speedup on P processors is defined to be t_1/t_P, where t_1 is the running time on 1 processor, and t_P is the running time on P processors.  Conversely, we can think about the speedup graph as plotting a function f(x), which we expect to be generally increasing with x.  Then the running-time graph plots a function akin to 1/f(x), whose values tend to be similar for larger inputs x.  That's why we tend to see the values in the running-time plot pressed together for larger numbers of workers, even when the corresponding values are spread out in the speedup plot.

The tool uses `lscpu --parse` to examine the configuration of hardware threads on the system to try to determine several things: which hardware threads represent distinct processor cores, how hardware threads are organized among sockets on the system, and which hardware threads appear due to hyperthreading.  The `lscpu --parse` command is a standard Linux command that you should be able to run from the command line on different machines to see what it's doing.

We've tested the tool on modern Linux systems running on modern Intel processors, but I'm not sure if `lscpu --parse` produces notably different output on AMD Opterons.  If possible, could you please share the output of `lscpu --parse` when run on your previous 64-core machine?  That output might help us diagnose the behavior of the tool on that machine.

For some context, here's some motivation behind the tool using this `lscpu` command, primarily driven by hardware trends on Intel processors.

**Dealing with Intel hyperthreading**  Modern Intel processors support hyperthreading, which allows two distinct threads run simultaneously on the same physical processor core.  Hyperthreading can improve program performance, but not as much as a separate physical core.  (Roughly speaking, we tend to find that using a second hyperthread on the same physical core gives at most 20% of the performance of using a distinct physical core, and can actually hurt performance on some programs.)  But under Linux, hyperthreads appear as distinct hardware threads, very much like distinct processor cores.  If one is not careful in measuring performance on different processor counts, one can see unexpected performance trends due to mistakenly using hyperthreads instead of distinct physical cores.

To mitigate the effects of hyperthreading, the tool examines the output of `lscpu --parse` to identify which Linux hardware threads correspond with distinct processor cores and which correspond with hyperthreads.  The tool then runs the program using only the distinct processor cores, which generally means it uses only half of the Linux hardware threads.

**Dealing with multiple sockets**  On multisocket systems, the output of `lscpu --parse` can also identify which physical processor cores belong to the same processor chip, or socket.  Because of modern hardware features such as NUMA and shared caches, it's not uncommon for parallel program performance to get worse when the processor cores running the program are distributed across sockets, instead of consolidated to the same socket.

To help users spot performance anomalies due to running on multiple sockets, the tool uses the output of `lscpu --parse` to identify cores that share the same socket, and then, when running a program on increasing worker counts, it will use `taskset` to pin workers to processor cores on the same socket before adding workers running on cores on different sockets.  The plotting tools adds vertical dotted lines to the plot to identify when workers end up distributed across multiple sockets.

Hopefully that makes sense.  Please let us know if you have more questions.

Cheers,
TB

**Comment by AminSahebi** [comment]
Dear Tao, 

Sorry for the long delay, I was busy with some deadlines,
Many thanks for your comprehensive explanation. 

I temporarily made it working, I commented the lines 78-81 of the runner.py, and the tool could recognize the 64 available cores, however, I don't know the side effects of this (what actually "added-nodes" do), I tried with MatrixMultiply and Fibonacci, which worked for my case.

(line 78-81)
https://github.com/OpenCilk/productivity-tools/blob/153a1e05ef3554d44f9ee4eb4bf614b67d709c8c/Cilkscale_vis/runner.py#L77

Anyway, I attached the output of the "lscpu --parse" command for our two AMD machines, please have a look.

[tfx2-lscpu-parse.txt](https://github.com/OpenCilk/productivity-tools/files/6327242/tfx2-lscpu-parse.txt)
[tfx3-lscpu-parse.txt](https://github.com/OpenCilk/productivity-tools/files/6327243/tfx3-lscpu-parse.txt)


Many thanks 
Amin
