### ISSUE TITLE
Reporting work and span in the number of instructions

### ISSUE THREAD

**Issue by qtt2** [OpenCilk/productivity-tools#17]
Hi,

Does cilkscale support reporting work and span in the number of instructions (e.g., X86 instructions) instead of seconds? Something like what is shown in the cilkview paper (http://web.mit.edu/willtor/www/res/cilkview-spaa-10.pdf - Figure 6).

Thanks,

Tuan

**Comment by neboat** [comment]
Hey Tuan,

Cilkscale supports something similar, though not quite the same. If you use `-fcilktool=cilkscale-instructions`, instead of `-fcilktool=cilkscale`, then Cilkscale will measure work and span in terms of pseudoinstructions, which is essentially a weighted instruction count based on LLVM's internal cost model.  The pseudoinstruction count does not correspond directly to X86 instructions, but it may serve your needs.

I've mostly used this pseudoinstruction-based version for debugging Cilkscale, since it produces deterministic work and span measurements (assuming the program-under-test is itself deterministic).  But I've also noticed that it tends to run more slowly than the ordinary time-based version of Cilkscale.

Feel free to try out this pseudoinstruction-based version of Cilkscale yourself, and let us know if it works for you.

Cheers,
TB

**Comment by qtt2** [comment]
Thank Tao!
